# Generated by Django 4.1.4 on 2023-01-07 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('currency_name', models.CharField(default='Nigerian Naira', max_length=100)),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('bill_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('evidence', models.FileField(blank=True, upload_to='')),
                ('notes', models.TextField(blank=True)),
                ('total_amount_due', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Total amount to be paid')),
                ('total_amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Total amount already paid')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_collected', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('settled', 'Settled'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_participants', to='bills.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_participant_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('contribution', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Bill contribution of participant (excludes fees)')),
                ('total_payment', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Total amount paid (includes fees)')),
                ('paystack_transaction_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('paystack_transfer_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('halver_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('settled', 'Settled'), ('declined', 'Declined')], max_length=10)),
                ('paystack_transaction_reference', models.CharField(blank=True, max_length=100)),
                ('paystack_transfer_reference', models.CharField(blank=True, max_length=100)),
                ('refundable', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bills.bill')),
                ('bill_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bills.billparticipant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='participants',
            field=models.ManyToManyField(related_name='bills', through='bills.BillParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('contribution', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Bill contribution of participant (excludes fees)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('paystack_transaction_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('paystack_transfer_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('halver_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.bill')),
                ('bill_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.billparticipant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
