# Generated by Django 4.1.4 on 2023-03-24 09:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('currency_name', models.CharField(default='Nigerian Naira', max_length=100)),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('first_charge_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='')),
                ('interval', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('none', 'None')], default='none', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount_due', models.DecimalField(decimal_places=4, help_text='Total amount to be paid', max_digits=19)),
                ('is_discreet', models.BooleanField(default=False, help_text='Are transactions and actions hidden from non-creditor, non-creator participants')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('contribution', models.DecimalField(decimal_places=4, help_text='Bill contribution of participant (excludes fees)', max_digits=19, null=True)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('opted_out', 'Opted out'), ('pending_transfer', 'Pending transfer'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('last_payment_failed', 'Last payment failed')], default='pending', max_length=50)),
                ('paystack_transaction_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('paystack_transfer_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('halver_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('total_payment_due', models.DecimalField(decimal_places=4, help_text='Summation of contribution and total fees. Actual amount to be paid', max_digits=19, null=True)),
            ],
            options={
                'verbose_name': 'Bill action',
                'verbose_name_plural': 'Bill actions',
            },
        ),
        migrations.CreateModel(
            name='BillArrear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('status', models.CharField(choices=[('overdue', 'Overdue'), ('forgiven', 'Forgiven'), ('pending_transfer', 'Pending transfer'), ('completed', 'Completed')], default='overdue', max_length=50)),
                ('contribution', models.DecimalField(decimal_places=4, help_text='Bill contribution of participant (excludes fees)', max_digits=19, null=True)),
                ('paystack_transaction_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('paystack_transfer_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('halver_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('total_payment_due', models.DecimalField(decimal_places=4, help_text='Summation of contribution and total fees. Actual amount to be paid', max_digits=19, null=True)),
            ],
            options={
                'verbose_name': 'Bill arrear',
                'verbose_name_plural': 'Bill arrears',
            },
        ),
        migrations.CreateModel(
            name='BillUnregisteredParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'Bill unregistered participant',
                'verbose_name_plural': 'Bill unregistered participants',
            },
        ),
        migrations.CreateModel(
            name='BillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('contribution', models.DecimalField(decimal_places=4, help_text='Bill contribution of participant (excludes fees)', max_digits=19)),
                ('transaction_type', models.CharField(choices=[('regular', 'Regular'), ('arrear', 'Arrear')], default='regular', max_length=50)),
                ('total_payment', models.DecimalField(decimal_places=4, help_text='Total amount paid (includes fees)', max_digits=19)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='halver_transactions', to='bills.billaction')),
                ('arrear', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halver_transaction', to='bills.billarrear')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bills.bill')),
            ],
            options={
                'verbose_name': 'Bill transaction',
                'verbose_name_plural': 'Bill transactions',
            },
        ),
    ]
