# Generated by Django 4.1.4 on 2023-01-12 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="participants",
        ),
        migrations.AddField(
            model_name="bill",
            name="participants",
            field=models.ManyToManyField(
                related_name="bills", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="action",
            name="bill_participant",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="bill_participant",
        ),
        migrations.DeleteModel(
            name="BillParticipant",
        ),
    ]
