# Generated by Django 4.1.4 on 2023-03-24 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtransaction',
            name='paystack_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='halver_transaction', to='financials.paystacktransaction'),
        ),
        migrations.AddField(
            model_name='billtransaction',
            name='paystack_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='halver_transaction', to='financials.paystacktransfer'),
        ),
        migrations.AddField(
            model_name='billarrear',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrears', to='bills.billaction'),
        ),
        migrations.AddField(
            model_name='billarrear',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='billarrear',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billaction',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='billaction',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billaction',
            name='unregistered_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.billunregisteredparticipant'),
        ),
        migrations.AddField(
            model_name='bill',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='participants',
            field=models.ManyToManyField(related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='unregistered_participants',
            field=models.ManyToManyField(related_name='bills', to='bills.billunregisteredparticipant'),
        ),
    ]
