# Generated by Django 4.1.7 on 2023-05-14 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='contribution',
            field=models.DecimalField(decimal_places=4, help_text='Bill contribution of participant (excludes fees)', max_digits=19, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
