# Generated by Django 4.1.4 on 2023-01-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_action_bill_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='due_date',
            new_name='deadline',
        ),
    ]
