# Generated by Django 4.1.7 on 2023-05-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_billtransaction_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtransaction',
            old_name='participant',
            new_name='paying_user',
        ),
        migrations.RenameField(
            model_name='billtransaction',
            old_name='recipient',
            new_name='receiving_user',
        ),
    ]
