# Generated by Django 4.1.4 on 2023-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_user_action_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='refundable',
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('declined', 'Declined'), ('pending_transfer', 'Pending Transfer'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=50),
        ),
    ]
