# Generated by Django 4.1.4 on 2023-01-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_remove_paystackplan_action_and_more'),
        ('bills', '0005_remove_transaction_refundable_alter_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='paystack_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='financials.paystackplan'),
        ),
        migrations.AddField(
            model_name='action',
            name='paystack_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paystack_subscription', to='financials.paystacksubscription'),
        ),
        migrations.AlterField(
            model_name='action',
            name='contribution',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True, verbose_name='Bill contribution of participant (excludes fees)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='halver_fee',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='paystack_transaction_fee',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='paystack_transfer_fee',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='total_fee',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
