# Generated by Django 4.1.7 on 2023-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rename_participant_billtransaction_paying_user_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billunregisteredparticipant',
            index=models.Index(fields=['phone'], name='bills_billu_phone_d24dee_idx'),
        ),
    ]
