# Generated by Django 4.1.7 on 2023-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_billunregisteredparticipant_bills_billu_phone_d24dee_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('arrear', 'Arrear')], default='regular', max_length=10),
        ),
        migrations.AddIndex(
            model_name='billaction',
            index=models.Index(fields=['status'], name='bills_billa_status_128093_idx'),
        ),
        migrations.AddIndex(
            model_name='billarrear',
            index=models.Index(fields=['status'], name='bills_billa_status_4351bc_idx'),
        ),
    ]
