# Generated by Django 4.1.7 on 2023-06-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_billtransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billarrear',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billtransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billunregisteredparticipant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['uuid'], name='bills_bill_uuid_3cac77_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['name'], name='bills_bill_name_3674f7_idx'),
        ),
    ]
