# Generated by Django 4.1.4 on 2023-01-25 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='first_charge_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 5, 55, 24, 115187), null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='next_charge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
