# Generated by Django 4.1.4 on 2023-01-25 19:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_remove_bill_bill_date_bill_first_charge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='first_charge_date',
            field=models.DateTimeField(blank=True, default=core.utils.get_one_week_from_now, null=True),
        ),
    ]
