# Generated by Django 4.1.7 on 2023-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_bill_created_alter_billaction_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaction',
            name='status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('opted_out', 'Opted out'), ('pending_transfer', 'Pending transfer'), ('failed_transfer', 'Failed transfer'), ('reversed_transfer', 'Reversed transfer'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('last_payment_failed', 'Last payment failed')], default='pending', max_length=50),
        ),
    ]
