# Generated by Django 4.1.4 on 2023-02-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_bill_first_charge_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
