# Generated by Django 4.1.7 on 2023-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_billaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billarrear',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('forgiven', 'Forgiven'), ('pending_transfer', 'Pending transfer'), ('failed_transfer', 'Failed transfer'), ('reversed_transfer', 'Reversed transfer'), ('completed', 'Completed')], default='overdue', max_length=50),
        ),
    ]
