# Generated by Django 4.1.4 on 2023-02-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0012_rename_action_billaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billaction',
            name='paystack_plan',
        ),
        migrations.RemoveField(
            model_name='billaction',
            name='paystack_subscription',
        ),
        migrations.AddField(
            model_name='bill',
            name='is_discreet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billaction',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billaction',
            name='status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('declined', 'Declined'), ('pending_transfer', 'Pending Transfer'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='BillUnregisteredParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Duplicate phone numbers are not allowed.'}, max_length=128, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contribution', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Bill contribution of unregistered participant')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_participants', to='bills.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='billaction',
            name='unregistered_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.billunregisteredparticipant'),
        ),
    ]
