# Generated by Django 4.1.4 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_remove_billaction_paystack_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaction',
            name='total_payment_due',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True, verbose_name='Summation of contribution and total fees. Actual amount to be paid'),
        ),
    ]
