# Generated by Django 4.1.4 on 2023-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_billaction_total_payment_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billaction',
            options={'verbose_name': 'Bill action', 'verbose_name_plural': 'Bill actions'},
        ),
        migrations.AlterModelOptions(
            name='billtransaction',
            options={'verbose_name': 'Bill transaction', 'verbose_name_plural': 'Bill transactions'},
        ),
        migrations.AlterModelOptions(
            name='billunregisteredparticipant',
            options={'verbose_name': 'Bill unregistered participant', 'verbose_name_plural': 'Bill unregistered participants'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_discreet',
            field=models.BooleanField(default=False, verbose_name='Are transactions and actions hidden from non-creditor, non-creator participants'),
        ),
    ]
