# Generated by Django 4.1.4 on 2023-02-26 14:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_alter_bill_options_alter_billaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billunregisteredparticipant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
