# Generated by Django 4.1.4 on 2023-03-01 09:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_alter_bill_interval_alter_bill_is_discreet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billunregisteredparticipant',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billunregisteredparticipant',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='billunregisteredparticipant',
            name='email',
        ),
        migrations.AddField(
            model_name='bill',
            name='unregistered_participants',
            field=models.ManyToManyField(related_name='bills', to='bills.billunregisteredparticipant'),
        ),
        migrations.AlterField(
            model_name='billunregisteredparticipant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=128, region=None, unique=True),
        ),
    ]
