# Generated by Django 4.1.4 on 2023-03-01 10:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_alter_billunregisteredparticipant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billunregisteredparticipant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=128, region=None, unique=True),
        ),
    ]
