# Generated by Django 4.1.4 on 2023-03-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_alter_billaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='billtransaction',
            name='halver_fee',
        ),
        migrations.RemoveField(
            model_name='billtransaction',
            name='paystack_transaction_fee',
        ),
        migrations.RemoveField(
            model_name='billtransaction',
            name='paystack_transfer_fee',
        ),
        migrations.RemoveField(
            model_name='billtransaction',
            name='total_fee',
        ),
        migrations.AddField(
            model_name='billtransaction',
            name='action',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='halver_transaction', to='bills.billaction'),
        ),
    ]
