# Generated by Django 4.1.4 on 2023-03-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_remove_bill_total_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='halver_transaction', to='bills.billaction'),
        ),
    ]
