# Generated by Django 4.1.4 on 2023-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_alter_billtransaction_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='next_charge_date',
        ),
    ]
