# Generated by Django 4.1.4 on 2023-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0025_alter_bill_uuid_alter_billaction_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='interval',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
