# Generated by Django 4.1.4 on 2023-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_alter_bill_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='first_charge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
