# Generated by Django 4.1.4 on 2023-03-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0027_alter_bill_first_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='halver_transactions', to='bills.billaction'),
        ),
    ]
