# Generated by Django 4.1.4 on 2023-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0029_billtransaction_transaction_type_billarrear'),
    ]

    operations = [
        migrations.AddField(
            model_name='billarrear',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('completed', 'Completed')], default='overdue', max_length=50),
        ),
    ]
