# Generated by Django 4.1.4 on 2023-03-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0031_billarrear_action_billtransaction_arrear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billarrear',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrears', to='bills.billaction'),
        ),
    ]
