# Generated by Django 4.1.4 on 2023-01-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='uuid',
        ),
    ]
