# Generated by Django 4.1.7 on 2023-10-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expo_push_token',
            field=models.CharField(blank=True, error_messages={'unique': 'This token already exists for a different user.'}, max_length=70, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['expo_push_token'], name='expo_push_token_index'),
        ),
    ]
