# Generated by Django 4.1.4 on 2022-12-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('first6', models.CharField(blank=True, max_length=10, verbose_name="Card's first 6 numbers (bin)")),
                ('card_type', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('exp_month', models.CharField(blank=True, max_length=10)),
                ('exp_year', models.CharField(blank=True, max_length=10)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
