# Generated by Django 4.1.4 on 2022-12-29 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('first6', models.CharField(blank=True, max_length=10, verbose_name="Card's first 6 digits (bin)")),
                ('card_type', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('exp_month', models.CharField(blank=True, max_length=10)),
                ('exp_year', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('last4', models.CharField(blank=True, max_length=4, verbose_name="Card's last 4 digits")),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('is_default', models.BooleanField(default=False)),
                ('recipient_code', models.CharField(blank=True, max_length=100)),
                ('recipient_type', models.CharField(choices=[('authorization', 'Card'), ('nuban', 'Account')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
