# Generated by Django 4.1.7 on 2023-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
