# Generated by Django 4.1.7 on 2023-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_transferrecipient_bank_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paystacktransaction',
            index=models.Index(fields=['paystack_transaction_id'], name='financials__paystac_aebe4e_idx'),
        ),
    ]
