# Generated by Django 4.1.4 on 2023-01-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_transferrecipient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrecipient',
            options={'ordering': ['-created', 'user'], 'verbose_name': "User's Transfer Recipient", 'verbose_name_plural': "User's Transfer Recipients"},
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'ordering': ['-created', 'user'], 'verbose_name': "User's Card", 'verbose_name_plural': "User's Cards"},
        ),
    ]
