# Generated by Django 4.1.4 on 2023-01-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_transferrecipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country where card was issued'),
        ),
    ]
