# Generated by Django 4.1.4 on 2023-01-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_usercard_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrecipient',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'User Transfer Recipient', 'verbose_name_plural': 'User Transfer Recipients'},
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'User Card', 'verbose_name_plural': 'User Cards'},
        ),
    ]
