# Generated by Django 4.1.7 on 2023-06-02 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0004_alter_paystackplan_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransfer',
            name='paying_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paystack_transfers_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
