# Generated by Django 4.1.4 on 2023-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_transferrecipient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='recipient_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='authorization_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='bank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Country where card was issued'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='first6',
            field=models.CharField(max_length=10, verbose_name="Card's first 6 digits (bin)"),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='last4',
            field=models.CharField(max_length=4, verbose_name="Card's last 4 digits"),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='signature',
            field=models.CharField(max_length=100),
        ),
    ]
