# Generated by Django 4.1.7 on 2023-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_paystacktransfer_paying_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransfer',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
