# Generated by Django 4.1.4 on 2023-01-20 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_user_action_participant_and_more'),
        ('financials', '0006_alter_transferrecipient_recipient_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=50)),
                ('plan_code', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount to be paid within each interval')),
                ('complete_paystack_data', models.JSONField()),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_plan', to='bills.action')),
            ],
            options={
                'verbose_name': 'Paystack Plan',
                'verbose_name_plural': 'Paystack Plans',
                'ordering': ['-created'],
            },
        ),
    ]
