# Generated by Django 4.1.7 on 2023-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_paystacktransfer_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paystacktransfer',
            index=models.Index(fields=['paystack_transfer_reference'], name='financials__paystac_0e4584_idx'),
        ),
        migrations.AddIndex(
            model_name='paystacktransfer',
            index=models.Index(fields=['transfer_outcome'], name='financials__transfe_6db9bd_idx'),
        ),
    ]
