# Generated by Django 4.1.4 on 2023-01-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_paystackplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackPlan',
        ),
    ]
