# Generated by Django 4.1.7 on 2023-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_paystacktransfer_financials__paystac_0e4584_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransfer',
            name='transfer_outcome',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('retried', 'Retried')], max_length=50),
        ),
    ]
