# Generated by Django 4.1.4 on 2023-01-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_paystackplan_paystacktransfer_paystacktransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackplan',
            name='action',
        ),
        migrations.RemoveField(
            model_name='paystacksubscription',
            name='action',
        ),
    ]
