# Generated by Django 4.1.7 on 2023-08-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_alter_paystacktransfer_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='recipient_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='signature',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='transferrecipient',
            constraint=models.UniqueConstraint(fields=('user', 'recipient_code'), name='user_recipient_code_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='transferrecipient',
            constraint=models.UniqueConstraint(fields=('user', 'authorization_code', 'associated_card'), name='user_authorization_code_associated_card_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('user', 'signature'), name='user_signature_uniqueness'),
        ),
    ]
