# Generated by Django 4.1.4 on 2023-01-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_remove_paystackplan_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecipient',
            name='account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='associated_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_transfer_recipient', to='financials.usercard'),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='bank_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='name',
            field=models.CharField(default='Ini', max_length=100),
            preserve_default=False,
        ),
    ]
