# Generated by Django 4.1.4 on 2023-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_transferrecipient_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='bank_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
