# Generated by Django 4.1.4 on 2023-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_alter_transferrecipient_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecipient',
            name='complete_paystack_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usercard',
            name='complete_paystack_response',
            field=models.JSONField(default=dict),
        ),
    ]
