# Generated by Django 4.1.4 on 2023-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_transferrecipient_complete_paystack_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='complete_paystack_response',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='complete_paystack_response',
            field=models.JSONField(),
        ),
    ]
