# Generated by Django 4.1.4 on 2023-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_alter_transferrecipient_complete_paystack_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecipient',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
