# Generated by Django 4.1.4 on 2023-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_transferrecipient_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='paystacksubscription',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='paystacktransfer',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='recipient_type',
            field=models.CharField(choices=[('authorization', 'Card'), ('nuban', 'Bank account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='complete_paystack_response',
            field=models.JSONField(editable=False),
        ),
    ]
