# Generated by Django 4.1.4 on 2023-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_alter_paystackplan_complete_paystack_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='refundable_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
