# Generated by Django 4.1.4 on 2023-01-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_paystacktransaction_refundable_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='first6',
            new_name='first_6',
        ),
        migrations.RenameField(
            model_name='usercard',
            old_name='last4',
            new_name='last_4',
        ),
        migrations.AddField(
            model_name='usercard',
            name='brand',
            field=models.CharField(default='visa', max_length=100),
        ),
        migrations.AddField(
            model_name='usercard',
            name='channel',
            field=models.CharField(default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='usercard',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
