# Generated by Django 4.1.4 on 2023-01-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0018_rename_first6_usercard_first_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='channel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='reusable',
            field=models.BooleanField(),
        ),
    ]
