# Generated by Django 4.1.4 on 2023-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0019_alter_usercard_brand_alter_usercard_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='paystack_transaction_reference',
            field=models.CharField(default='random', max_length=100),
        ),
    ]
