# Generated by Django 4.1.4 on 2023-01-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0020_paystacktransaction_paystack_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='paystack_transaction_reference',
            field=models.CharField(max_length=100),
        ),
    ]
