# Generated by Django 4.1.4 on 2023-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0021_alter_paystacktransaction_paystack_transaction_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystackplan',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'Paystack plan', 'verbose_name_plural': 'Paystack plans'},
        ),
        migrations.AlterModelOptions(
            name='paystacksubscription',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'Paystack subscription', 'verbose_name_plural': 'Paystack subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='paystacktransaction',
            options={'ordering': ['-created'], 'verbose_name': 'Paystack transaction', 'verbose_name_plural': 'Paystack transactions'},
        ),
        migrations.AlterModelOptions(
            name='paystacktransfer',
            options={'ordering': ['-created'], 'verbose_name': 'Paystack transfer', 'verbose_name_plural': 'Paystack transfers'},
        ),
        migrations.AlterModelOptions(
            name='transferrecipient',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'User transfer recipient', 'verbose_name_plural': 'User transfer recipients'},
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'ordering': ['-created', 'user'], 'verbose_name': 'User card', 'verbose_name_plural': 'User cards'},
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('participant-payment', 'Participant payment'), ('card-addition', 'Card addition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paystacktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('creditor-settlement', 'Creditor settlement'), ('card-addition-refund', 'Card addition refund')], max_length=50),
        ),
    ]
