# Generated by Django 4.1.4 on 2023-02-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0022_alter_paystackplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='recipient_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='signature',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
