# Generated by Django 4.1.4 on 2023-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0023_alter_transferrecipient_recipient_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecipient',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
