# Generated by Django 4.1.4 on 2023-02-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_remove_billaction_paystack_plan_and_more'),
        ('financials', '0025_paystackplan_action_paystacksubscription_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paystack_plan', to='bills.billaction'),
        ),
        migrations.AlterField(
            model_name='paystacksubscription',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paystack_subscription', to='bills.billaction'),
        ),
    ]
