# Generated by Django 4.1.4 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0026_alter_paystackplan_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackplan',
            name='complete_paystack_payload',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paystacksubscription',
            name='complete_paystack_payload',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
