# Generated by Django 4.1.4 on 2023-02-28 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_alter_bill_interval_alter_bill_is_discreet_and_more'),
        ('financials', '0028_alter_paystackplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaystackPlanFailures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('failure_message', models.CharField(max_length=150)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paystack_plan_failure', to='bills.billaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
