# Generated by Django 4.1.4 on 2023-02-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0017_alter_bill_interval_alter_bill_is_discreet_and_more'),
        ('financials', '0029_alter_paystackplan_interval_paystackplanfailures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystackplanfailures',
            options={'verbose_name': 'Paystack plan failure', 'verbose_name_plural': 'Paystack plans failures'},
        ),
        migrations.RenameField(
            model_name='paystacksubscription',
            old_name='user',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='paystackplan',
            name='user',
        ),
        migrations.AddField(
            model_name='paystackplan',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystackplan',
            name='unregistered_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_plans', to='bills.billunregisteredparticipant'),
        ),
        migrations.AddField(
            model_name='paystackplanfailures',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_plan_failures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystackplanfailures',
            name='unregistered_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_plan_failures', to='bills.billunregisteredparticipant'),
        ),
    ]
