# Generated by Django 4.1.4 on 2023-02-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0030_alter_paystackplanfailures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
