# Generated by Django 4.1.4 on 2023-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0031_alter_paystackplan_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystackplanfailures',
            options={'verbose_name': 'Paystack plan failure', 'verbose_name_plural': 'Paystack plan failures'},
        ),
        migrations.AlterField(
            model_name='paystackplan',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text="Amount to be paid within each interval, in kobo (or other subunit), according to Paystack's standard approach.", max_digits=19, verbose_name='Amount in Kobo or other subunit'),
        ),
    ]
