# Generated by Django 4.1.4 on 2023-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0032_alter_paystackplanfailures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('participant_payment', 'Participant payment'), ('card_addition', 'Card addition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paystacktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('creditor_settlement', 'Creditor settlement'), ('card_addition_refund', 'Card addition refund')], max_length=50),
        ),
    ]
