# Generated by Django 4.1.4 on 2023-03-07 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0034_paystackplan_amount_in_naira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='paystackplanfailures',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='paystacksubscription',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='paystacktransfer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='transferrecipient',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
