# Generated by Django 4.1.4 on 2023-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0036_remove_paystacksubscription_complete_paystack_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackplan',
            name='interval',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=50),
        ),
    ]
