# Generated by Django 4.1.4 on 2023-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0037_alter_paystackplan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('one_time_contribution', 'One-time contribution'), ('subscription_contribution', 'Subscription contribution'), ('card_addition', 'Card addition')], max_length=50),
        ),
    ]
