# Generated by Django 4.1.4 on 2023-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0039_paystacksubscription_paystack_subscription_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubscription',
            name='paystack_subscription_code',
            field=models.CharField(max_length=100),
        ),
    ]
