# Generated by Django 4.1.4 on 2023-03-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0031_billarrear_action_billtransaction_arrear_and_more'),
        ('financials', '0041_rename_paystackplanfailures_paystackplanfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='arrear',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paystack_transaction', to='bills.billarrear'),
        ),
        migrations.AddField(
            model_name='paystacktransfer',
            name='arrear',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paystack_transfer', to='bills.billarrear'),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('one_time_contribution', 'One-time contribution'), ('arrear_contribution', 'Arrear contribution'), ('subscription_contribution', 'Subscription contribution'), ('card_addition', 'Card addition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paystacktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('creditor_settlement', 'Creditor settlement'), ('arrear_settlement', 'Arrear settlement'), ('card_addition_refund', 'Card addition refund')], max_length=50),
        ),
    ]
