# Generated by Django 4.1.4 on 2023-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0042_paystacktransaction_arrear_paystacktransfer_arrear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacksubscription',
            name='paystack_email_token',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
