# Generated by Django 4.1.4 on 2023-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0043_paystacksubscription_paystack_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubscription',
            name='paystack_email_token',
            field=models.CharField(max_length=100),
        ),
    ]
