# fly.toml file generated for halver on 2023-03-25T13:12:26+01:00

app = "halver"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
[processes]
app = "poetry run gunicorn --bind :8000 --workers 2 core.wsgi:application"
worker = "poetry run celery -A core worker -l info"
flower = "poetry run celery -A core flower"
beat = "poetry run celery -A core beat -l info"


[env]
PORT = "8000"

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[statics]]
guest_path = "/code/staticfiles"
url_prefix = "/static/"


[[services]]
internal_port = 5555
processes = ["flower"]
protocol = "tcp"
[services.concurrency]
hard_limit = 10
soft_limit = 5
type = "connections"

[[services.ports]]
handlers = ["tls", "http"]
port = 5555


[[services]]
internal_port = 5556
processes = ["worker"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["tls", "http"]
port = 5556


[[services]]
internal_port = 5557
processes = ["beat"]
protocol = "tcp"
[services.concurrency]
hard_limit = 10
soft_limit = 5
type = "connections"

[[services.ports]]
handlers = ["tls", "http"]
port = 5557
